

54000it [00:05, 9583.64it/s]

6000it [00:00, 9383.77it/s]
train_Accuracy =  0.8666481481481482 train_Loss :  0.3750743144308517 val_Accuracy: 0.8635 val_loss: 0.38176727198873367


51532it [00:05, 7691.08it/s]
54000it [00:05, 10111.71it/s]
6000it [00:00, 10454.29it/s]
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/confusion_matrix.py", line 66, in <module>
    plt.imshow(confusion_matrix(truth_labels,pred_labels,normalise='True'),cmap='viridis')
  File "/home/sandeep/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 189, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'normalise'
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/confusion_matrix.py", line 66, in <module>
    plt.imshow(confusion_matrix(truth_labels,pred_labels,normalise='True'),cmap='viridis')
  File "/home/sandeep/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 189, in wrapper
    params = func_sig.bind(*args, **kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3186, in bind
    return self._bind(args, kwargs)
  File "/usr/lib/python3.10/inspect.py", line 3175, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'normalise'