

54000it [00:05, 10064.36it/s]
6000it [00:00, 10855.05it/s]
train_Accuracy =  0.8668888888888889 train_Loss :  0.3729054164555925 val_Accuracy: 0.8568333333333333 val_loss: 0.37972868443086116
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/confusion_matrix.py", line 66, in <module>
    plt.imshow(confusion_matrix(truth_labels,pred_labels,normalize='True'),cmap='viridis')
  File "/home/sandeep/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 201, in wrapper
    validate_parameter_constraints(
  File "/home/sandeep/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'normalize' parameter of confusion_matrix must be a str among {'all', 'true', 'pred'} or None. Got 'True' instead.
Traceback (most recent call last):
  File "/home/sandeep/Documents/IITM/Deep Learning/confusion_matrix.py", line 66, in <module>
    plt.imshow(confusion_matrix(truth_labels,pred_labels,normalize='True'),cmap='viridis')
  File "/home/sandeep/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 201, in wrapper
    validate_parameter_constraints(
  File "/home/sandeep/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'normalize' parameter of confusion_matrix must be a str among {'all', 'true', 'pred'} or None. Got 'True' instead.