2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Configure stats pid to 379242
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Loading settings from /home/sandeep/.config/wandb/settings
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Loading settings from /home/sandeep/Documents/IITM/Deep Learning/wandb/settings
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/sandeep/Documents/IITM/Deep Learning/main.py', 'program': '/home/sandeep/Documents/IITM/Deep Learning/main.py'}
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_init.py:_log_setup():526] Logging user logs to /home/sandeep/Documents/IITM/Deep Learning/wandb/run-20240304_233339-v3guzogf/logs/debug.log
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_init.py:_log_setup():527] Logging internal logs to /home/sandeep/Documents/IITM/Deep Learning/wandb/run-20240304_233339-v3guzogf/logs/debug-internal.log
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_init.py:init():566] calling init triggers
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_init.py:init():616] starting backend
2024-03-04 23:33:39,675 INFO    MainThread:379242 [wandb_init.py:init():620] setting up manager
2024-03-04 23:33:39,677 INFO    MainThread:379242 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-04 23:33:39,679 INFO    MainThread:379242 [wandb_init.py:init():628] backend started and connected
2024-03-04 23:33:39,682 INFO    MainThread:379242 [wandb_init.py:init():720] updated telemetry
2024-03-04 23:33:39,690 INFO    MainThread:379242 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-04 23:33:40,430 INFO    MainThread:379242 [wandb_run.py:_on_init():2262] communicating current version
2024-03-04 23:33:40,664 INFO    MainThread:379242 [wandb_run.py:_on_init():2271] got version response 
2024-03-04 23:33:40,664 INFO    MainThread:379242 [wandb_init.py:init():804] starting run threads in backend
2024-03-04 23:33:40,715 INFO    MainThread:379242 [wandb_run.py:_console_start():2241] atexit reg
2024-03-04 23:33:40,716 INFO    MainThread:379242 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-04 23:33:40,716 INFO    MainThread:379242 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-04 23:33:40,716 INFO    MainThread:379242 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-04 23:33:40,717 INFO    MainThread:379242 [wandb_init.py:init():847] run started, returning control to user process
2024-03-04 23:33:42,134 INFO    MainThread:379242 [pyagent.py:run():324] Starting sweep agent: entity=None, project=None, count=100
2024-03-04 23:33:50,351 WARNING MsgRouterThr:379242 [router.py:message_loop():77] message_loop has been closed
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Configure stats pid to 379242
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Loading settings from /home/sandeep/.config/wandb/settings
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Loading settings from /home/sandeep/Documents/IITM/Deep Learning/wandb/settings
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'test', 'entity': 'ee23s059', 'root_dir': '/home/sandeep/Documents/IITM/Deep Learning', 'sweep_id': 'f6ygsqdp', 'run_id': 'dj10vsqm', 'sweep_param_path': '/home/sandeep/Documents/IITM/Deep Learning/wandb/sweep-f6ygsqdp/config-dj10vsqm.yaml'}
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/sandeep/Documents/IITM/Deep Learning/main.py', 'program': '/home/sandeep/Documents/IITM/Deep Learning/main.py'}
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_init.py:_log_setup():526] Logging user logs to /home/sandeep/Documents/IITM/Deep Learning/wandb/run-20240304_233354-dj10vsqm/logs/debug.log
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_init.py:_log_setup():527] Logging internal logs to /home/sandeep/Documents/IITM/Deep Learning/wandb/run-20240304_233354-dj10vsqm/logs/debug-internal.log
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_init.py:init():566] calling init triggers
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_init.py:init():573] wandb.init called with sweep_config: {'activation_para': 'sigmoid', 'batch': 32, 'epochs': 10, 'lr': 0.001, 'n_hidden_layers': 3, 'optimiser': 'rms', 's_hidden_layers': 128, 'weight_decay': 0.5, 'weight_para': 'Xavier'}
config: {}
2024-03-04 23:33:54,216 INFO    Thread-5 (_run_job):379242 [wandb_init.py:init():611] wandb.init() called when a run is still active
2024-03-04 23:33:54,449 ERROR   Thread-5 (_run_job):379242 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 612, in init
    with telemetry.context() as tel:
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 759, in _telemetry_callback
    self._telemetry_flush()
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 770, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/sandeep/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
